"""empty message

Revision ID: f0284a5a2b22
Revises: c531256192b2
Create Date: 2021-05-28 18:12:25.912613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0284a5a2b22'
down_revision = 'c531256192b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('address', sa.String(length=150), nullable=True))
    op.drop_column('contact', 'adress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('adress', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('contact', 'address')
    # ### end Alembic commands ###
